---
- name: Install system packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python
    - python-dev
    - python-pip
    - python3
    - python3-pip
    - python3-dev
  become: yes
